[options]
admin_passwd = change-this-development-password
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/marine,/mnt/extra-addons/people,/mnt/extra-addons/supply,/mnt/extra-addons/customer,/mnt/extra-addons/platform,/mnt/extra-addons/demo
data_dir = /var/lib/odoo
list_db = True
dbfilter = ^sedar_demo$
proxy_mode = False
