version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "${ODOO_PORT:-8069}:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo/community/account-financial-reporting/account_financial_report:/mnt/extra-addons/account_financial_report
      - ./odoo/community/server-ux/date_range:/mnt/extra-addons/date_range
      - ./odoo/community/reporting-engine/report_xlsx:/mnt/extra-addons/report_xlsx
      - ./odoo/community/reporting-engine/report_xlsx_helper:/mnt/extra-addons/report_xlsx_helper
      - ./odoo/community/mis-builder/mis_builder:/mnt/extra-addons/mis_builder
      - ./odoo/community/account-financial-reporting/mis_template_financial_report:/mnt/extra-addons/mis_template_financial_report
      - ./odoo/community/account-financial-reporting/mis_builder_cash_flow:/mnt/extra-addons/mis_builder_cash_flow
      - ./odoo/community/account-financial-reporting/partner_statement:/mnt/extra-addons/partner_statement
      - odoo-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf

volumes:
  db-data:
  odoo-data:
