{
    'name': 'SEDAR Operations Integration',
    'version': '17.0.1.0.0',
    'summary': 'Connected request-to-cash and operational readiness workflows',
    'category': 'Operations',
    'license': 'LGPL-3',
    'depends': [
        'sedar_marketing',
        'sedar_tug_ops',
        'sedar_crewing',
        'sedar_hsse',
        'sedar_doccontrol',
        'sedar_dashboard',
        'sedar_marine_mvp',
        'maintenance',
        'purchase_stock',
        'sedar_procurement',
        'hr_attendance',
        'hr_holidays',
        'account_financial_report',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/legacy_view_cleanup.xml',
        'data/maintenance_data.xml',
        'data/finance_data.xml',
        'data/procurement_data.xml',
        'data/inventory_data.xml',
        'views/workflow_views.xml',
        'views/hse_workflow_views.xml',
        'views/document_workflow_views.xml',
        'views/maintenance_workflow_views.xml',
        'data/presentation_data.xml',
        'data/hse_presentation_data.xml',
        'data/maintenance_presentation_data.xml',
        'data/finance_presentation_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sedar_operations_integration/static/src/css/document_risk_dashboard.css',
        ],
    },
    'installable': True,
    'application': False,
}
